name: PerlTest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
    - run: sudo apt-get install -y muscle hmmer raxml
    - run: curl http://molevol.cmima.csic.es/castresana/Gblocks/Gblocks_Linux64_0.91b.tar.Z | tar xz
    - run: echo "$PWD/Gblocks_0.91b" >> $GITHUB_PATH
    - run: cpanm --installdeps .
    - run: prove -lv t